---
papersize: a4
fontsize: 12pt
mainfont: "Times New Roman"
geometry: margin=2.5cm

linestretch: 1.5
indent: 0.5in

bibliography: ./references.bib
csl: ./format/style.csl

header-includes:
  - \usepackage{ragged2e}
  - \usepackage{graphicx}

  - \usepackage{fancyhdr}

  - \usepackage{titlesec}
  - \titleformat{\section}[block]{\centering\bfseries\Large}{\thesection}{1em}{}

  - \addtocontents{toc}{\protect\thispagestyle{empty}}

  - \usepackage{csvsimple, longtable}
  - \newcommand\tsv[1]{\csvautolongtable[respect all, separator=tab]{#1.tsv}}
---

